# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'db_table': 'Available',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numberofmembers', models.IntegerField(blank=True, db_column='numberOfMembers', null=True)),
                ('projectid', models.IntegerField(blank=True, db_column='projectId', null=True)),
            ],
            options={
                'db_table': 'Groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('projectid', models.IntegerField(db_column='projectId')),
            ],
            options={
                'db_table': 'Idea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('classname', models.CharField(blank=True, db_column='className', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languagesdesired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagename', models.CharField(db_column='languageName', max_length=20)),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'LanguagesDesired',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languagesknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagename', models.CharField(db_column='languageName', max_length=20)),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'LanguagesKnown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField(db_column='groupId')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
            ],
            options={
                'db_table': 'PartOf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'db_table': 'Preferred',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.IntegerField(db_column='projectId', primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(blank=True, db_column='groupId', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skillsdesired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('skillname', models.CharField(db_column='skillName', max_length=20)),
            ],
            options={
                'db_table': 'SkillsDesired',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skillsknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('skillname', models.CharField(db_column='skillName', max_length=20)),
            ],
            options={
                'db_table': 'SkillsKnown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('netid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('yearinschool', models.CharField(blank=True, db_column='yearInSchool', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField(db_column='groupId')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
            ],
            options={
                'db_table': 'Suggested',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(db_column='netId', max_length=10)),
                ('instructorname', models.CharField(db_column='instructorName', max_length=50)),
            ],
            options={
                'db_table': 'Teaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'db_table': 'Times',
                'managed': False,
            },
        ),
    ]
